### ISSUE TITLE
Bug: Assertion function not behaving as expected

### ISSUE THREAD

**Issue by kumar-praveen-k** [Jozty/website#33]
**Describe the bug**
Assertion function not behaving as expected for false case

**To Reproduce**
Code- 
`console.assert(3===5) // false`
Playground link- https://fae.jozty.io/playground?code=aW1wb3J0ICogYXMgRmFlIGZyb20gImZhZUB2MS4xLjAiCgpjb25zb2xlLmFzc2VydChGYWUuYWRkKDEsIDIpID09PSAzKQpjb25zb2xlLmFzc2VydChGYWUuYWRkKDEsIC0yKSA9PT0gLTEpCgpjb25zdCBwbHVzNSA9IEZhZS5hZGQoNSkKCmNvbnNvbGUuYXNzZXJ0KHBsdXM1KDMpID09PSAzKQpjb25zb2xlLmFzc2VydChwbHVzNSgtNykgPT09IC0yKQpjb25zb2xlLmFzc2VydChwbHVzNSgwKSA9PT0gNSkKCmNvbnNvbGUubG9nKCdFeGFtcGxlIHJhbiBzdWNjZXNzZnVsbHknKQo.&version=v1.1.0

**Expected behavior**
Should print an Error when  the assertion is false

**Comment by singla-shivam** [comment]
Thank you @kumar-praveen-k for the issue.

> The `console.assert()` method writes an error message to the console if the assertion is false. If the assertion is true, nothing happens.

As mentioned in the docs, `console.assert` prints the error to `stderr`, but it does not throw an error. It means the script still exits with exit code `0` (if everything goes well). Thus, "Assertion failed" is sent to `stderr` and still the script runs to completion and prints the successful message.

As in below code,

https://github.com/Jozty/website/blob/c7774a2/utilities/exec.js#L6-L7

We are only sending `stdout` in case of no error (that is script ends with `0`). That's why we are only printing the `stdout`, that is the successful message. The fix the issue would sending both `stderr` and `stdout` to the calling function and then sending it the frontend playground when a script is run.
